import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const api = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:5000' }),
  tagTypes:['comments'], //this for refetch comment after add comment
  endpoints: () => ({}),
});

//  export const {useGetProductQuery,
//   useGetSingleProductQuery,
//   usePostCommentMutation,useGetCommentQuery} = api
//  //! useGetProductQuery --> holo autogen react hook. builder method er surute getProduct nam
//  //! thekei , useGetProductQuery autogenerated hoyeche . ai hook theke data , data-loading , error etc handle kora jabe

// export type UseGetSingleProductQueryType = ReturnType<
//   typeof useGetSingleProductQuery
// >;
