import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const api = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:5000' }),
  tagTypes:['comments'], //this for refetch comment after add comment
  endpoints: (builder) => ({
    //! rtk query autogen vabe atkti hooks dey, ekhane getProduct ai nam onusare autogen hook debe
    getProduct: builder.query({
      query: () => '/products',
      //! query: (dynamic vabe data pete params dite hoy)=> " ekhane route dite hoy"
    }),

    getSingleProduct: builder.query({
      query: (id) => `/product/${id}`,
    }),

    postComment: builder.mutation({
      query: ({ id, ...data }) => ({
        url: `/comment/${id}`,
        method: 'POST',
        body: data,
      }),
      invalidatesTags:['comments']

    }),

    getComment: builder.query({
      query: (id) => `/comment/${id}`,
      providesTags:['comments']
    }),
  }),
});

 export const {useGetProductQuery,
  useGetSingleProductQuery,
  usePostCommentMutation,useGetCommentQuery} = api
 //! useGetProductQuery --> holo autogen react hook. builder method er surute getProduct nam
 //! thekei , useGetProductQuery autogenerated hoyeche . ai hook theke data , data-loading , error etc handle kora jabe

export type UseGetSingleProductQueryType = ReturnType<
  typeof useGetSingleProductQuery
>;
